/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
	interface RouteList {
		"boost.browser-logs": [],
		"cashier.payment": [
			{
				"name": "id",
				"required": true
			}
		],
		"cashier.webhook": [],
		"welcome": [],
		"register": [],
		"register.store": [],
		"login": [],
		"login.store": [],
		"logout": [],
		"password.request": [],
		"password.email": [],
		"verification.notice": [],
		"verification.verify": [
			{
				"name": "id",
				"required": true
			},
			{
				"name": "hash",
				"required": true
			}
		],
		"verification.send": [],
		"dashboard": [],
		"admin.dashboard": [],
		"budgets.index": [],
		"budgets.create": [],
		"budgets.store": [],
		"budgets.show": [
			{
				"name": "budget",
				"required": true,
				"binding": "id"
			}
		],
		"budgets.edit": [
			{
				"name": "budget",
				"required": true,
				"binding": "id"
			}
		],
		"budgets.update": [
			{
				"name": "budget",
				"required": true,
				"binding": "id"
			}
		],
		"budgets.destroy": [
			{
				"name": "budget",
				"required": true,
				"binding": "id"
			}
		],
		"budgets.expenses.store": [
			{
				"name": "budget",
				"required": true,
				"binding": "id"
			}
		],
		"expenses.update": [
			{
				"name": "expense",
				"required": true,
				"binding": "id"
			}
		],
		"expenses.destroy": [
			{
				"name": "expense",
				"required": true,
				"binding": "id"
			}
		],
		"subscription.checkout": [
			{
				"name": "plan",
				"required": true
			}
		],
		"subscription.manage": [],
		"plans": [],
		"subscription.swap": [
			{
				"name": "plan",
				"required": true
			}
		],
		"subscription.cancel": [],
		"subscription.resume": [],
		"billing": [],
		"billing.success": [],
		"billing.cancel": [],
		"budgets.chat": [
			{
				"name": "budget",
				"required": true,
				"binding": "id"
			}
		],
		"budgets.scan-ticket": [
			{
				"name": "budget",
				"required": true,
				"binding": "id"
			}
		],
		"settings.profile": [],
		"settings.profile.update": [],
		"settings.password": [],
		"settings.password.update": [],
		"storage.local": [
			{
				"name": "path",
				"required": true
			}
		],
		"storage.local.upload": [
			{
				"name": "path",
				"required": true
			}
		]
	}
}
export {};
